### ISSUE TITLE
AndroidX Migration

### ISSUE THREAD

**Issue by cybvitthal** [wcoder/MaterialChipView#10]
Library still uses Xamarin.Android.Support.v4 (>= 28.0.0) and Xamarin.Android.Support.v7.AppCompat (>= 28.0.0).
Do you plan to migrate to AndroidX

**Comment by cybvitthal** [comment]
@wcoder , Is the library still maintained?

**Comment by yauhenipakala** [comment]
@cybvitthal yes, still maintained
Sorry for the delay, I can update this library this week.

**Comment by yauhenipakala** [comment]
@cybvitthal new version ready for use: https://www.nuget.org/packages/MaterialChipView/1.2.5.2

**Comment by yauhenipakala** [comment]
Also, look at #7 for using Chip from Google Material library.
