### ISSUE TITLE
Unnecessary allocations of TextView and view not updating on property changes

### ISSUE THREAD

**Issue by codedevote** [wcoder/MaterialChipView#2]
In Chip class there is a method InitTextView() that is called from different places. It is not only called on initialization, but also on touch of selection or closed button. 
On each call it allocates a new TextView and adds it to the layout's view collection. See https://github.com/wcoder/MaterialChipView/blob/49344c67714f5c5686dee4071d1412fae45b7b8d/src/MaterialChipView/Chip.cs#L391
That's obviously sth. that needs to be fixed. 
Also, if the Chip is already displayed, it does not update, when ChipText or BackgroundColor property are changed.

I already have a PR, since those two things are rather small fixes, I put them in this single issue.

**Comment by yauhenipakala** [comment]
Fixed #6
