### ISSUE TITLE
Selection of Chip only works when taping on the tick icon.

### ISSUE THREAD

**Issue by ndlovucn** [wcoder/MaterialChipView#5]
Selection of Chip only works when taping on the tick icon. It will make for a better user experience when the selection action registers when a user clicks any where on the body of the chip and not only on the selection tick icon.

I have tried to programmatically set 
`chip.Selectable = true;` 
or even  doing 
`chip.ChildAt(1).PerformClick()` 

All my attempts have not yielded the desired outcome

**Comment by yauhenipakala** [comment]
Hi @ndlovucn 
You can check the latest v1.2.5  (PR #6 )
