### ISSUE TITLE
Can not set SpannableString to chip text

### ISSUE THREAD

**Issue by cybDevendra** [wcoder/MaterialChipView#8]
Hi @wcoder ,
Could you please provide any property to set SpannableString to chip text. So we can add custom text to it. E.g. textView.SetText("chip text",TextView.BufferType.Spannable)

**Comment by cybDevendra** [comment]
Hello @wcoder ,
Actually, we're using this library as nuget package in our Xamarin native project. Now, our requirement is to use formatted text i.e. SpannableString in Chip, but currently, there is no option to do in this library. could you please check and provide any solution for this?

Thanks in Advance :)

**Comment by yauhenipakala** [comment]
Hi @cybDevendra ! Thanks for the feature request!

I have created a new NuGet package with this ability [v1.2.5.1](https://www.nuget.org/packages/MaterialChipView/1.2.5.1)
Also, you can check version changes: https://github.com/wcoder/MaterialChipView/pull/9/commits/a3fe4efdb94ff1c53e71dab0a743636ca6227d6f

Now you can use this syntax:
```cs
var span = new SpannableString("My Football");
span.SetSpan(new ForegroundColorSpan(Color.Red), 0, 2, 0);  // "My" is red
_chipLabel.ChipSpanText = span;
```
